### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by morcason** [biocoder-frodo/FRITZBox-SynologyLogCenterDaemon#8]
Hi there,
while running script I get this error message:

PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /volume1/homes/morcason/FRITZBox-SynologyLogCenterDaemon-master/FritzLuaLog.php:17
Stack trace:
#0 /volume1/homes/morcason/FRITZBox-SynologyLogCenterDaemon-master/FritzLuaLog.php(58): FritzLuaLog->parselogs(Object(stdClass), '')
#1 /volume1/homes/morcason/FRITZBox-SynologyLogCenterDaemon-master/fritzbox-syslog-daemon.php(105): FritzLuaLog->getlogs('')
#2 {main}
  thrown in /volume1/homes/morcason/FRITZBox-SynologyLogCenterDaemon-master/FritzLuaLog.php on line 17

**Comment by morcason** [comment]
solved, (-j option)
THANK YOU!
